version: "3.9"

services:
  mongo:
    image: mongo:8.0.4
    ports:
      - '27019:27017'
    volumes:
      - ./docker/data/mongo/db:/data/db
    networks:
      - default
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: book-review-api
    ports:
      - "3000:3000"
    environment:
      DD_SERVICE: book-review-api
      DD_ENV: dev
      DD_VERSION: "1.0.0"

      DD_AGENT_HOST: datadog-agent
      DD_TRACE_AGENT_PORT: 8126

      DD_LOGS_INJECTION: "true"
      NODE_ENV: development
    depends_on:
      mongo:
        condition: service_healthy
      book-api:
        condition: service_started
      datadog-agent:
        condition: service_started
    networks:
      - default

  book-api:
    build: ./PS_Task_2
    container_name: book-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/profitsoft
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    depends_on:
      datadog-agent:
        condition: service_started
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail http://localhost:8080/actuator/health || exit 1" ]
      interval: 15s
      timeout: 5s
      retries: 8
    networks:
      - default

  datadog-agent:
    image: gcr.io/datadoghq/agent:7
    container_name: datadog-agent
    environment:
      DD_API_KEY: ${DD_API_KEY}
      DD_SITE: datadoghq.eu

      DD_APM_ENABLED: "true"
      DD_DOGSTATSD_NON_LOCAL_TRAFFIC: "true"

      DD_PROCESS_AGENT_ENABLED: "false"

      DD_LOGS_ENABLED: "true"
      DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL: "true"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro

    ports:
      - "8126:8126"
      - "8125:8125/udp"

volumes:
  mongodb-data:
    driver: local
    name: mongo-data
  mongodb-log:
    driver: local
    name: mongo-log

networks:
  default:
    driver: bridge